### PR TITLE
A few cleanups and another signature

### PR DESCRIPTION
**Pull request by alexpearce**
Tried to improve the style of a few things. I will open another PR for actual ideas, if I can up with any.

### CODE REVIEW

**Comment by alexpearce** [comment]
Let me know when you're ready to merge this and I will rebase to fix the merge conflicts (so that you can click the Big Green Button :white_check_mark:).

**Comment by particleist** [comment]
Right, because you were not working off the head I don't think...? I like
it so please fix the conflicts.

**Comment by alexpearce** [comment]
Because commits have been made since this PR was opened, and they conflict with the proposed changes.

Should be good to go now :rocket:

**Comment by particleist** [comment]
Thanks Alex, great stuff.

**Pull request merged**
